### ISSUE TITLE
1.12.2 Server Crash

### ISSUE THREAD

**Issue by Yamza** [DoubleDoorDevelopment/OpLock#1]
Running MC Eternal 1.3.7.1

Crash Report: https://pastebin.com/4QP9bqPr
Server Log: https://gist.githubusercontent.com/Yamza/d0b9a7d76d6ebfdf798d607dd917f96c/raw/b20de49d351d87a5d482c50e572988b4677441c9/gistfile1.txt

**Comment by Claycorp** [comment]
Attempted fix is in 1.0.2.
Feel free to open again if it's not fixed.
